project_name: ticker
before:
  hooks:
    - go mod download
builds:
  - id: build-upx
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    hooks:
      post:
        - upx "{{ .Path }}"
  - id: build
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    replacements:
      darwin: mac
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
release:
  github:
      owner: achannarasappa
      name: ticker
# brews:
#   -
#     name: ticker
#     tap:
#       owner: achannarasappa
#       name: tap
#     commit_author:
#       name: achannarasappa
#       email: git@ani.dev
#     homepage: "https://github.com/achannarasappa/ticker"
#     description: "Terminal stock ticker with live updates and position tracking"
#     license: "GPLv3"
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    ids:
    - ticker
    image_templates:
    - "ghcr.io/junior/ticker:latest"
    - "ghcr.io/junior/ticker:{{ .Tag }}"
    - "ghcr.io/junior/ticker:v{{ .Major }}"
    dockerfile: Dockerfile

    # Whether to use `docker buildx build` instead of `docker build`.
    # You probably want to set it to true when using flags like `--platform`.
    # If true, will also add `--load` to the build flags.
    # Defaults to false.
    # use_buildx: true

    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"